//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTasksProject.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iTasksProject.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iletişim.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görevlerini organize etmekten yoruldun mu ?.
        /// </summary>
        public static string Definition1 {
            get {
                return ResourceManager.GetString("Definition1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to her şeyini aynı anda hatırlayamıyor musun ?.
        /// </summary>
        public static string Definition2 {
            get {
                return ResourceManager.GetString("Definition2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTasks senin ihtiyacındır..
        /// </summary>
        public static string Definition3 {
            get {
                return ResourceManager.GetString("Definition3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTasks Nedir ?.
        /// </summary>
        public static string Definition4 {
            get {
                return ResourceManager.GetString("Definition4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTasks uygulaması, iTasks hesabınızla birlikte görevlerinizi yönetmenize, organize etmenize ve kaydetmenize olanak tanır..
        /// </summary>
        public static string Definition5 {
            get {
                return ResourceManager.GetString("Definition5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ios / android uygulamamızı indirin ve görevinizi telefonunuzla bilgisayarınız arasında senkronize edin..
        /// </summary>
        public static string Definition6 {
            get {
                return ResourceManager.GetString("Definition6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görevlerinize bir hesapla herhangi bir cihazdan erişin.
        /// </summary>
        public static string Definition7 {
            get {
                return ResourceManager.GetString("Definition7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        public static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görevlerim.
        /// </summary>
        public static string MyTasks {
            get {
                return ResourceManager.GetString("MyTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydol.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydol şimdi.
        /// </summary>
        public static string RegisterNow {
            get {
                return ResourceManager.GetString("RegisterNow", resourceCulture);
            }
        }
    }
}
