//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTasksProject.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iTasksProject.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifremi değiştir.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapıldı.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iletişim.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bize mesaj bırakın.
        /// </summary>
        public static string Contact1 {
            get {
                return ResourceManager.GetString("Contact1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        public static string Contact2 {
            get {
                return ResourceManager.GetString("Contact2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email adres.
        /// </summary>
        public static string Contact3 {
            get {
                return ResourceManager.GetString("Contact3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konu.
        /// </summary>
        public static string Contact4 {
            get {
                return ResourceManager.GetString("Contact4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajınız.
        /// </summary>
        public static string Contact5 {
            get {
                return ResourceManager.GetString("Contact5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajı gönder.
        /// </summary>
        public static string Contact6 {
            get {
                return ResourceManager.GetString("Contact6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizi ziyaret edin.
        /// </summary>
        public static string Contact7 {
            get {
                return ResourceManager.GetString("Contact7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google haritalarında bizi bulursunuz.
        /// </summary>
        public static string Contact8 {
            get {
                return ResourceManager.GetString("Contact8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iletişim mesajları.
        /// </summary>
        public static string ContactMessages {
            get {
                return ResourceManager.GetString("ContactMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Günlük.
        /// </summary>
        public static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GÜNLÜK GÖREVLER.
        /// </summary>
        public static string DailyTasks {
            get {
                return ResourceManager.GetString("DailyTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görevlerini organize etmekten yoruldun mu ?.
        /// </summary>
        public static string Definition1 {
            get {
                return ResourceManager.GetString("Definition1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to her şeyini aynı anda hatırlayamıyor musun ?.
        /// </summary>
        public static string Definition2 {
            get {
                return ResourceManager.GetString("Definition2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTasks senin ihtiyacındır..
        /// </summary>
        public static string Definition3 {
            get {
                return ResourceManager.GetString("Definition3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTasks Nedir ?.
        /// </summary>
        public static string Definition4 {
            get {
                return ResourceManager.GetString("Definition4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTasks uygulaması, iTasks hesabınızla birlikte görevlerinizi yönetmenize, organize etmenize ve kaydetmenize olanak tanır..
        /// </summary>
        public static string Definition5 {
            get {
                return ResourceManager.GetString("Definition5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ios / android uygulamamızı indirin ve görevinizi telefonunuzla bilgisayarınız arasında senkronize edin..
        /// </summary>
        public static string Definition6 {
            get {
                return ResourceManager.GetString("Definition6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görevlerinize bir hesapla herhangi bir cihazdan erişin.
        /// </summary>
        public static string Definition7 {
            get {
                return ResourceManager.GetString("Definition7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanııc sil.
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştir.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgilerimi değiştir.
        /// </summary>
        public static string EditInfo {
            get {
                return ResourceManager.GetString("EditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hedef.
        /// </summary>
        public static string Goal {
            get {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEDEFLER.
        /// </summary>
        public static string Goals {
            get {
                return ResourceManager.GetString("Goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhaba.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önemli.
        /// </summary>
        public static string Important {
            get {
                return ResourceManager.GetString("Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        public static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin yap.
        /// </summary>
        public static string MakeAdmin {
            get {
                return ResourceManager.GetString("MakeAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönet.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görevlerim.
        /// </summary>
        public static string MyTasks {
            get {
                return ResourceManager.GetString("MyTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon numarası eklenmedi.
        /// </summary>
        public static string NoPhoneNum {
            get {
                return ResourceManager.GetString("NoPhoneNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon numarası.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öncelik.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydol.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydol şimdi.
        /// </summary>
        public static string RegisterNow {
            get {
                return ResourceManager.GetString("RegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatırlatıcı.
        /// </summary>
        public static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamanlanmış.
        /// </summary>
        public static string Scheduled {
            get {
                return ResourceManager.GetString("Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yükle.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görev.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşte burada günlük yaptığınız görevler.
        /// </summary>
        public static string Tasks1 {
            get {
                return ResourceManager.GetString("Tasks1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşte burada haftalık yaptığınız görevler.
        /// </summary>
        public static string Tasks2 {
            get {
                return ResourceManager.GetString("Tasks2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulaşmak istediğiniz hedefler.
        /// </summary>
        public static string Tasks3 {
            get {
                return ResourceManager.GetString("Tasks3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tür.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapılmadı.
        /// </summary>
        public static string Uncomplete {
            get {
                return ResourceManager.GetString("Uncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya seç.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kullanıcı adı.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcılar.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çok önemli.
        /// </summary>
        public static string VeryImportant {
            get {
                return ResourceManager.GetString("VeryImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haftalık.
        /// </summary>
        public static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAFTALIK GÖREVLER.
        /// </summary>
        public static string WeeklyTasks {
            get {
                return ResourceManager.GetString("WeeklyTasks", resourceCulture);
            }
        }
    }
}
